### ISSUE TITLE
Notifications Not Properly Working

### ISSUE THREAD

**Issue by lawfulsoftware** [tiredofit/docker-freescout#126]
I am running 1.8.69 using the PHP 8.2 version (:latest).

I have the Mentions module.  These are the only notifications that I receive.

Under my profile (/users/notifications/), I have all Browser Notifications turned on except for the following:

- A conversation is assigned to someone else
- To an unassigned conversation (both)
- To a conversation owned by someone else (both)

I have not once received a notification of a new conversation or that a conversation has been assigned to me.  All users report the same.

**Comment by tiredofit** [comment]
This might be a good issue for the main Freescout repo. Otherwise, you could try running the PHP 8.1 or 8.0 variant of the image and see if it happens still. You can see here how I name the other versions: https://hub.docker.com/repository/docker/tiredofit/freescout/tags?page=1&ordering=last_updated
