### ISSUE TITLE
Compatibility with Podman

### ISSUE THREAD

**Issue by freescout-helpdesk** [tiredofit/docker-freescout#182]
### Summary

There is such thing as [Podman](https://docs.podman.io/en/latest/), it's compatible with Docker images and allows to use them. We've got an information from one user that when FreeScout Docker image is used with Podman most PHP and Nginx config files are empty, so it does not work properly. We ourselves tried to use this Docker image with Podman but bumped into another error...

Have anyone actually managed to use this FreeScout Docker image with Podman?

**Comment by tiredofit** [comment]
Podman will generally run most OCI containers, but has differences in the way that it operates. One of the major ones being that it opens container execution operations to users who do not have elevated privileges, where as docker typically requires root. Another large difference would be the lack of a central socket to view or send information to the docker API. There are a handful of other larger differences that I bump into regularly..

More than likely the most common issue would be that the user would be running Docker in a rootless environment where the container itself is creating and expecting access internally as root to create folders and volumes resulting in empty directories. I've worked around that in the past but it involves swapping out some core functionality (like the init system) in my base images, essentially removing a significant amount of their functional capabilities.

The user could revert to Podman volumes as opposed to bind mounts which may give them what they need. I'm not sure however why the PHP and Nginx configuration files would be empty as the problems one would normally see would be interaction with files _outside_ of the container.. 

If 100% operation under Podman is required for FreeScout I'd be recommending to start with another image entirely, there are too many differences which cause problems because it's only partially compatible with Docker..

**Comment by freescout-helpdesk** [comment]
Thanks a lot.

**Comment by freescout-helpdesk** [comment]
FYI. With the latest version of Podman everything works just fine (under root user and under rootless environment).

Thanks again.
