### ISSUE TITLE
Support non-dockerized reverse proxies

### ISSUE THREAD

**Issue by kri** [tiredofit/docker-freescout#19]
We're having trouble getting docker-freescout to run in an environment where the reverse proxy runs out-of-docker.

nginx and certbot are already installed on that host; we don't use them via docker. Hence, we chose to set up the [no-proxy](https://github.com/tiredofit/docker-freescout/blob/master/examples/docker-compose-no-proxy.yml) configuration and quickly noticed that all the URLs start with `http:` instead of `https:`, making login attempts fail [1] due to some scripts not loading.

What we then tried to do was to set `ENABLE_SSL_PROXY=TRUE`, though that caused our freescout subdomain to get caught in an infinite 302 loop redirecting to itself.

@tiredofit: Is there a way to make your container work in such an environment?

----

[1] This bug has already been described in https://github.com/freescout-helpdesk/freescout/issues/502.

**Comment by tiredofit** [comment]
This sounds very similar to #18 - I wonder if it is because of the base image for nginx I am using.

From the nginx base image these are some environment variables that may help you

*Reverse Proxy Options*

| Parameter | Description |
|-----------|-------------|
| `NGINX_ENABLE_FASTCGI_HTTPS` | Set fastcgi_param HTTPS 'on' - Default `FALSE` |
| `NGINX_ENABLE_REVERSE_PROXY` | Helpers for when behind a reverse proxy - Default `TRUE` | 
| `NGINX_REAL_IP_HEADER` | What is the header passed containing the visitors IP - Default `X-Forwarded-For` | 
| `NGINX_SET_REAL_IP_FROM` | Set the network of your Docker Network if having IP lookup issues - Default `172.16.0.0/12` | 

I'll follow the the freescout issue and see if I can build in a fix into the image.

**Comment by kri** [comment]
Thanks for the pointers. For the scenario outlined above, I found that setting these environment variables will load the scripts just fine:

```
- ENABLE_SSL_PROXY=TRUE
- NGINX_ENABLE_FASTCGI_HTTPS=TRUE
```

I haven't thoroughly tested anything else yet, as it seems that my admin user isn't created, so I can't log in, nor can I reset my password. Since this is a whole different issue entirely, I'll close this one and will open another if I can't figure anything out.

Thank you!

**Comment by shunkica** [comment]
Since this is where Google led me when I had the same issue,  I will post the entire configuration which worked for me.

Your proxy must be pointed to the freescout port using http protocol, eg. if you are using apache for proxy:
```
<Location />
    ProxyPass http://127.0.0.1:8447/ nocanon
    ProxyPassReverse http://127.0.0.1:8447/
</Location>
```

And in the docker compose file for freescout you must have:
```
   ports:
     - 8447:80
```
And these environment variables:
```
     - SITE_URL=https://yourfreescout.com
     - ENABLE_SSL_PROXY=TRUE
     - NGINX_ENABLE_FASTCGI_HTTPS=TRUE
```
