### ISSUE TITLE
Problems configuring smtp

### ISSUE THREAD

**Issue by brase** [tiredofit/docker-freescout#25]
I tried different Methods to configure the smtp.

First I used the SMTP-Method in Freescout but there I always get a timeout.

Then I tried the built-in smtp configuration of the alpine container. Sending mails within the console works but not on freescout either. It is saying something about emtpy response.

Is there something wrong in freescout. Does anybody has an idea how to debug any further?

**Comment by tiredofit** [comment]
We'll need to know more details on the error, perhaps screenshots, or any info from log files. I haven't heard of any issues with outbound mail either on my own installations or here. Are you by chance being blocked at the provider level?

**Comment by brase** [comment]
Yeah, thought of this. Logging is a problem. I do not get any useful information out of the logs. The Error-Messages I see are only the ones in the ui.

I have to look at it again these days.

I do not think that there is a problem with the provider (as we are using a self hosted mailserver) as sending mails on the console within the container works.

Which mail configuration do you use? Sendmail or SMTP?

**Comment by tiredofit** [comment]
I use SMTP only so that the outgoing email can be saved as an archive on the mail server. We may have to look at the source code of Freescout in detail to see what is happening and perhaps make adjustments to how the containers `msmtp` command is being called (Replacement for sendmail). I experienced another issue coincidentally with another Laravel product and my base image over the past few days and wonder if they are related. I will try to investigate this week.
